version: '3.5'

services:
  db:
    env_file:
      - ./.env
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: postgres
    volumes:
      - ../../../../../docker/volumes/pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      - PORT=${API_PORT}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - '${API_PORT}:${API_PORT}'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  pgadmin:
    env_file:
      - ./.env
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '${PGADMIN_PORT}:80'
    depends_on:
      - db
